version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "automerge"

  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "automerge"
