import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, isAbsolute, relative } from "node:path";
import { spawn } from "node:child_process";
import type { CfStageConfig, DevCompanionConfig } from "../types.js";
import type { StateProvider } from "./state.js";
import { resolveDeployOrder } from "./graph.js";
import { assignPorts } from "./dev-ports.js";
import { createLogMultiplexer } from "./dev-logs.js";
import { findAvailablePorts } from "./port-finder.js";
import { readWranglerConfig } from "./wrangler.js";
import { renderWranglerConfig } from "./render.js";

export interface WorkerDevPlan {
  workerPath: string;
  cwd: string;
  configPath: string;
  port: number;
  args: string[];
  /** Env-var-name → deployed worker name (or null = missing from state, omit with warning). */
  serviceBindingFallbacks?: Record<string, string | null>;
}

export interface DevCompanionPlan {
  name: string;
  cwd: string;
  command: string;
  env?: Record<string, string>;
}

export interface WranglerSessionPlan {
  cwd: string;
  entryWorkerPath: string;
  workerPaths: string[];
  configPaths: string[];
  port: number;
  args: string[];
}

export interface DevPlan {
  mode: "workers" | "session";
  workers: WorkerDevPlan[];
  companions: DevCompanionPlan[];
  ports: Record<string, number>;
  session?: WranglerSessionPlan;
}

export interface DevOptions {
  basePort?: number;
  filter?: string;
  stage?: string;
  session?: boolean;
  persistTo?: string;
  workerOptions?: Record<string, { devPort?: number; devArgs?: string[] }>;
  /** Stage name to read fallback deployed-worker names from when --filter excludes service-binding targets. */
  fallbackStage?: string;
  /** State provider used to read fallback stage. Required when fallbackStage is set. */
  stateProvider?: StateProvider;
}

export interface DevHandle {
  /** Actual dev ports resolved at startup (worker path -> port). */
  ports: Record<string, number>;
  processes: Map<string, ReturnType<typeof spawn>>;
  stop(): Promise<void>;
}

function resolveWorkerConfigPath(rootDir: string, workerPath: string): string {
  const jsoncPath = resolve(rootDir, workerPath, "wrangler.jsonc");
  if (existsSync(jsoncPath)) return jsoncPath;

  const jsonPath = resolve(rootDir, workerPath, "wrangler.json");
  if (existsSync(jsonPath)) return jsonPath;

  throw new Error(
    `No wrangler.jsonc or wrangler.json found for worker "${workerPath}" at ${resolve(rootDir, workerPath)}`,
  );
}

function resolveDevPath(rootDir: string, path: string): string {
  return isAbsolute(path) ? path : resolve(rootDir, path);
}

function writeRenderedDevConfig(
  rootDir: string,
  stage: string,
  workerPath: string,
  config: CfStageConfig,
  state: Awaited<ReturnType<StateProvider["read"]>>,
): string {
  if (!state) {
    throw new Error(`Stage "${stage}" not found in state`);
  }

  const baseConfig = readWranglerConfig(resolve(rootDir, workerPath));
  const rendered = renderWranglerConfig(baseConfig, workerPath, config, state, stage, rootDir);
  const renderedPath = resolve(
    rootDir,
    ".wrangler-deploy",
    "dev",
    stage,
    workerPath,
    "wrangler.rendered.jsonc",
  );
  mkdirSync(resolve(renderedPath, "..", ".."), { recursive: true });
  mkdirSync(resolve(renderedPath, ".."), { recursive: true });
  writeFileSync(
    renderedPath,
    `// Auto-generated by wrangler-deploy. Do not edit.\n// Stage: ${stage} | Generated: ${new Date().toISOString()}\n${JSON.stringify(rendered, null, 2)}\n`,
  );
  return renderedPath;
}

/**
 * Collect transitive service-binding dependencies of a target worker.
 * Returns a set of worker paths including the target itself.
 */
function collectTransitiveDeps(
  target: string,
  serviceBindings: Record<string, Record<string, string>> | undefined,
): Set<string> {
  const result = new Set<string>();
  const queue = [target];

  while (queue.length > 0) {
    const current = queue.shift()!;
    if (result.has(current)) continue;
    result.add(current);

    const deps = serviceBindings?.[current];
    if (deps) {
      for (const dep of Object.values(deps)) {
        if (!result.has(dep)) {
          queue.push(dep);
        }
      }
    }
  }

  return result;
}

function buildCompanionPlans(
  rootDir: string,
  workers: string[],
  companions: DevCompanionConfig[] | undefined,
): DevCompanionPlan[] {
  if (!companions || companions.length === 0) return [];

  const includedWorkers = new Set(workers);
  return companions
    .filter((companion) => {
      if (!companion.workers || companion.workers.length === 0) return true;
      return companion.workers.some((worker) => includedWorkers.has(worker));
    })
    .map((companion) => ({
      name: companion.name,
      cwd: companion.cwd ? resolveDevPath(rootDir, companion.cwd) : rootDir,
      command: companion.command,
      env: companion.env,
    }));
}

/**
 * Build a dev plan: ordered list of workers with port and wrangler args.
 * Optionally filter to a target worker and its transitive service-binding deps.
 */
export async function buildDevPlan(
  config: CfStageConfig,
  rootDir: string,
  options: DevOptions,
): Promise<DevPlan> {
  const { basePort = 8787, filter, stage, workerOptions, fallbackStage, stateProvider } = options;

  if ((stage || fallbackStage) && !stateProvider) {
    throw new Error("stage/fallback-stage dev requires stateProvider — pass a StateProvider via DevOptions.stateProvider");
  }

  if (stage && fallbackStage) {
    throw new Error("stage and fallbackStage are not compatible — choose one source of stage state");
  }

  if (fallbackStage && stateProvider && (options.session ?? config.dev?.session?.enabled)) {
    throw new Error("read-mode (--fallback-stage) is not compatible with session mode — omit --session or --fallback-stage");
  }

  let workers: string[];
  const serviceBindingFallbacksByWorker = new Map<string, Record<string, string | null>>();
  let renderedConfigPathsByWorker = new Map<string, string>();
  let stageState: Awaited<ReturnType<StateProvider["read"]>> | undefined;

  if (stage && stateProvider) {
    stageState = await stateProvider.read(stage);
    if (!stageState) {
      throw new Error(`Stage "${stage}" not found in state`);
    }
  }

  if (filter) {
    const allWorkers = new Set(config.workers);
    if (!allWorkers.has(filter)) {
      throw new Error(`Unknown worker "${filter}" — not found in config. Available workers: ${[...allWorkers].join(", ")}`);
    }

    if (fallbackStage && stateProvider) {
      // Read-mode: only run the filter target; inject fallback bindings for its service binding targets.
      workers = [filter];

      const fallbackState = await stateProvider.read(fallbackStage);
      if (!fallbackState) {
        throw new Error(`Fallback stage "${fallbackStage}" not found in state`);
      }

      const directBindings = config.serviceBindings?.[filter] ?? {};
      const fallbacks: Record<string, string | null> = {};
      for (const [bindingEnvVar, targetWorkerPath] of Object.entries(directBindings)) {
        const workerEntry = fallbackState.workers[targetWorkerPath];
        if (!workerEntry) {
          console.warn(`  Warning: worker "${targetWorkerPath}" not found in fallback stage "${fallbackStage}" — omitting binding "${bindingEnvVar}"`);
          fallbacks[bindingEnvVar] = null;
        } else {
          fallbacks[bindingEnvVar] = workerEntry.name;
        }
      }
      if (Object.keys(fallbacks).length > 0) {
        serviceBindingFallbacksByWorker.set(filter, fallbacks);
      }
    } else {
      // Existing behavior: include transitive deps
      const deps = collectTransitiveDeps(filter, config.serviceBindings);
      const order = resolveDeployOrder(config);
      workers = order.filter((w) => deps.has(w));
    }
  } else {
    workers = resolveDeployOrder(config);
  }

  if (stage && stageState) {
    renderedConfigPathsByWorker = new Map(
      workers.map((workerPath) => [
        workerPath,
        writeRenderedDevConfig(rootDir, stage, workerPath, config, stageState),
      ]),
    );
  }

  const portOverrides: Record<string, number> = {};
  if (config.dev?.ports) {
    Object.assign(portOverrides, config.dev.ports);
  }
  if (workerOptions) {
    for (const [worker, opts] of Object.entries(workerOptions)) {
      if (opts.devPort !== undefined) {
        portOverrides[worker] = opts.devPort;
      }
    }
  }

  const filteredConfig: CfStageConfig = {
    ...config,
    workers,
    deployOrder: workers,
  };
  const ports = assignPorts(filteredConfig, basePort, portOverrides);

  const globalArgs = config.dev?.args ?? [];
  const workerPlans: WorkerDevPlan[] = workers.map((workerPath) => {
    const port = ports[workerPath]!;
    const customArgs = workerOptions?.[workerPath]?.devArgs ?? [];
    const serviceBindingFallbacks = serviceBindingFallbacksByWorker.get(workerPath);
    const configPath = renderedConfigPathsByWorker.get(workerPath) ?? resolveWorkerConfigPath(rootDir, workerPath);

    return {
      workerPath,
      cwd: resolve(rootDir, workerPath),
      configPath,
      port,
      args: [...globalArgs, ...customArgs],
      ...(serviceBindingFallbacks ? { serviceBindingFallbacks } : {}),
    };
  });

  const companions = buildCompanionPlans(rootDir, workers, config.dev?.companions);
  const sessionEnabled = options.session ?? config.dev?.session?.enabled ?? false;
  const persistTo = options.persistTo ?? config.dev?.session?.persistTo;

  if (sessionEnabled || options.persistTo !== undefined) {
    if (workerPlans.length === 0) {
      throw new Error("Cannot start a dev session without any workers.");
    }

    const entryWorkerPath =
      filter ?? config.dev?.session?.entryWorker ?? workerPlans[workerPlans.length - 1]!.workerPath;
    const entryWorker = workerPlans.find((worker) => worker.workerPath === entryWorkerPath);
    if (!entryWorker) {
      throw new Error(`Unable to resolve entry worker "${entryWorkerPath}" for local dev session.`);
    }

    const sessionWorkers = [
      entryWorker,
      ...workerPlans.filter((worker) => worker.workerPath !== entryWorker.workerPath),
    ];

    const sessionArgs: string[] = [];
    for (const worker of sessionWorkers) {
      sessionArgs.push("-c", worker.configPath);
    }
    if (persistTo) {
      sessionArgs.push("--persist-to", resolveDevPath(rootDir, persistTo));
    }
    sessionArgs.push(...globalArgs, ...(config.dev?.session?.args ?? []));

    return {
      mode: "session",
      workers: workerPlans,
      companions,
      ports: {
        [entryWorker.workerPath]: entryWorker.port,
      },
      session: {
        cwd: rootDir,
        entryWorkerPath: entryWorker.workerPath,
        workerPaths: sessionWorkers.map((worker) => worker.workerPath),
        configPaths: sessionWorkers.map((worker) => worker.configPath),
        port: entryWorker.port,
        args: sessionArgs,
      },
    };
  }

  return {
    mode: "workers",
    workers: workerPlans,
    companions,
    ports,
  };
}

function attachProcessLogs(
  proc: ReturnType<typeof spawn>,
  write: (chunk: string) => void,
): void {
  proc.stdout?.on("data", (data: Buffer) => write(data.toString()));
  proc.stderr?.on("data", (data: Buffer) => write(data.toString()));
}

function spawnCompanion(
  companion: DevCompanionPlan,
  env: Record<string, string>,
  write: (chunk: string) => void,
): ReturnType<typeof spawn> {
  const proc = spawn(companion.command, {
    cwd: companion.cwd,
    env: {
      ...process.env,
      ...env,
      ...(companion.env ?? {}),
    },
    shell: true,
  });
  attachProcessLogs(proc, write);
  return proc;
}

/**
 * Start dev servers for all workers in the plan.
 * Probes for available dev and inspector ports before spawning.
 * Pipes stdout/stderr through a log multiplexer.
 * Returns a handle to stop all processes.
 */
export async function startDev(
  plan: DevPlan,
  options?: { output?: (line: string) => void; logDir?: string; rootDir?: string },
): Promise<DevHandle> {
  const output = options?.output ?? ((line: string) => process.stdout.write(line + "\n"));
  const rootDir = options?.rootDir;
  const mux = createLogMultiplexer(output, { logDir: options?.logDir });
  const processes = new Map<string, ReturnType<typeof spawn>>();
  const resolvedPorts: Record<string, number> = {};
  let companionRuntimeEnv: Record<string, string> = {};

  if (plan.mode === "session") {
    const session = plan.session;
    if (!session) {
      throw new Error("Invalid dev plan: session mode requires session details.");
    }

    const usedPorts = new Set<number>();
    const [devPort] = await findAvailablePorts(session.port, 1, usedPorts);
    const [inspectorPort] = await findAvailablePorts(9229, 1, usedPorts);

    output("Starting local dev session:");
    output(`  ${session.entryWorkerPath} -> http://localhost:${devPort}`);
    if (session.workerPaths.length > 1) {
      output(`  includes: ${session.workerPaths.slice(1).join(", ")}`);
    }

    const write = mux.createWriter("wrangler");
    const proc = spawn(
      "npx",
      ["wrangler", "dev", "--port", String(devPort), "--inspector-port", String(inspectorPort), ...session.args],
      {
        cwd: session.cwd,
        shell: false,
      },
    );
    attachProcessLogs(proc, write);
    processes.set(`session:${session.entryWorkerPath}`, proc);
    resolvedPorts[session.entryWorkerPath] = devPort!;
    companionRuntimeEnv = {
      WD_DEV_ENTRY_WORKER: session.entryWorkerPath,
      WD_DEV_ENTRY_URL: `http://127.0.0.1:${devPort}`,
      WD_DEV_PORTS: JSON.stringify(resolvedPorts),
    };
  } else {
    const usedPorts = new Set<number>();
    const devPorts: number[] = [];
    for (const worker of plan.workers) {
      const [resolvedPort] = await findAvailablePorts(worker.port, 1, usedPorts);
      devPorts.push(resolvedPort!);
    }

    const inspectorPorts = await findAvailablePorts(9229, plan.workers.length, usedPorts);

    output("Starting dev servers:");
    for (let i = 0; i < plan.workers.length; i++) {
      const worker = plan.workers[i]!;
      const devPort = devPorts[i]!;
      output(`  ${worker.workerPath} -> http://localhost:${devPort}`);
    }

    for (let i = 0; i < plan.workers.length; i++) {
      const worker = plan.workers[i]!;
      const devPort = devPorts[i]!;
      const inspectorPort = inspectorPorts[i]!;

      // Write dev override config if worker has fallback service bindings
      let configOverridePath: string | undefined;
      if (rootDir && worker.serviceBindingFallbacks) {
        const activeFallbacks = Object.entries(worker.serviceBindingFallbacks).filter(
          ([, name]) => name !== null,
        );
        if (activeFallbacks.length > 0) {
          const overrideDir = resolve(rootDir, ".wrangler-deploy", "dev", worker.workerPath);
          const overridePath = resolve(overrideDir, "wrangler.dev.jsonc");
          mkdirSync(overrideDir, { recursive: true });
          const extendsPath = relative(overrideDir, worker.configPath);
          const overrideContent = {
            extends: extendsPath,
            services: activeFallbacks.map(([binding, service]) => ({ binding, service: service! })),
          };
          writeFileSync(overridePath, JSON.stringify(overrideContent, null, 2) + "\n");
          configOverridePath = overridePath;
        }
      }

      const args = [
        "dev",
        "--port", String(devPort),
        "--inspector-port", String(inspectorPort),
        ...(configOverridePath ? ["--config", configOverridePath] : []),
        ...worker.args,
      ];

      const write = mux.createWriter(worker.workerPath);
      const proc = spawn("npx", ["wrangler", ...args], {
        cwd: worker.cwd,
        shell: false,
      });

      attachProcessLogs(proc, write);
      processes.set(worker.workerPath, proc);
      resolvedPorts[worker.workerPath] = devPort;
    }
    companionRuntimeEnv = {
      WD_DEV_PORTS: JSON.stringify(resolvedPorts),
    };
  }

  if (plan.companions.length > 0) {
    output("Starting companion processes:");
    for (const companion of plan.companions) {
      output(`  ${companion.name} -> ${companion.command}`);
      const proc = spawnCompanion(companion, companionRuntimeEnv, mux.createWriter(companion.name));
      processes.set(`companion:${companion.name}`, proc);
    }
  }

  return {
    ports: resolvedPorts,
    processes,
    async stop() {
      await Promise.all(
        [...processes.values()].map(
          (proc) =>
            new Promise<void>((resolveStop) => {
              if (proc.exitCode !== null || proc.killed) {
                resolveStop();
                return;
              }

              const timeout = setTimeout(() => {
                resolveStop();
              }, 2_000);

              const done = () => {
                clearTimeout(timeout);
                resolveStop();
              };

              proc.once("exit", done);
              proc.once("error", done);
              proc.kill();
            }),
        ),
      );
    },
  };
}
