/**
 * Format resolved config as dotenv strings for wrangler --env-file.
 *
 * Uses single-quoted values by default — single-quoted values are treated
 * as literal strings with no escape processing, which avoids issues with
 * double quotes in JSON blobs and special characters.
 * Values containing single quotes fall back to double-quoted with escaping.
 */

import { addSerializedEnvToLines } from './chunking';

/**
 * Format a single KEY=VALUE line in dotenv format.
 * Uses single quotes for values that don't contain single quotes.
 * Falls back to double quotes with escaping for values containing single quotes.
 */
export function formatEnvLine(key: string, value: string): string {
  if (!value.includes("'")) {
    return `${key}='${value}'`;
  }
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  return `${key}="${escaped}"`;
}

export interface ResolvedEnvItem {
  value: unknown;
  isSensitive: boolean;
}

/**
 * Format resolved config as dotenv file content.
 *
 * @param config - Key-value pairs of resolved config
 * @param serializedEnvJson - Optional serialized env blob for runtime init
 * @param sensitivePrefixes - Keys starting with these prefixes are treated as sensitive (default: common secret prefixes)
 * @returns Dotenv-formatted string
 */
export function formatEnvFileContent(
  config: Record<string, { value: unknown; isSensitive?: boolean }>,
  serializedEnvJson?: string,
  _sensitivePrefixes: string[] = ['SECRET', 'KEY', 'PASSWORD', 'TOKEN', 'PRIVATE', 'API_KEY', 'DATABASE_URL'],
): string {
  const lines: string[] = [
    '# AUTO-GENERATED BY NODE-ENV-RESOLVER — DO NOT EDIT',
    `# ${process.platform === 'win32' ? 'This is a temporary file and will be cleaned up automatically.' : 'This file is served via a named pipe (FIFO) and exists only in memory.'}`,
    '# Your config schema is the source of truth.',
    '',
  ];

  for (const key in config) {
    const item = config[key];
    if (item.value === undefined) continue;
    const strValue = typeof item.value === 'string' ? item.value : JSON.stringify(item.value);
    lines.push(formatEnvLine(key, strValue));
  }

  if (serializedEnvJson !== undefined) {
    addSerializedEnvToLines(lines, serializedEnvJson, undefined, formatEnvLine);
  }

  return lines.join('\n');
}

/**
 * Determine if a config key is sensitive based on its name and explicit flag.
 */
export function isSensitiveKey(
  key: string,
  explicitFlag: boolean | undefined,
  sensitivePrefixes: string[] = ['SECRET', 'KEY', 'PASSWORD', 'TOKEN', 'PRIVATE', 'API_KEY', 'DATABASE_URL'],
): boolean {
  if (explicitFlag !== undefined) return explicitFlag;
  const upperKey = key.toUpperCase();
  return sensitivePrefixes.some((prefix) => upperKey.startsWith(prefix) || upperKey.includes(`_${prefix}`));
}

/**
 * Split resolved config into vars (non-sensitive) and secrets (sensitive).
 * Used for Cloudflare deploy: vars → --var flags, secrets → --secrets-file.
 */
export function splitConfigForDeploy(
  config: Record<string, { value: unknown; isSensitive?: boolean }>,
  sensitivePrefixes?: string[],
): { vars: Record<string, string>; secrets: Record<string, string> } {
  const vars: Record<string, string> = {};
  const secrets: Record<string, string> = {};

  for (const key in config) {
    const item = config[key];
    if (item.value === undefined) continue;
    const strValue = typeof item.value === 'string' ? item.value : JSON.stringify(item.value);

    if (isSensitiveKey(key, item.isSensitive, sensitivePrefixes)) {
      secrets[key] = strValue;
    } else {
      vars[key] = strValue;
    }
  }

  return { vars, secrets };
}
